server:
  port: 8888
spring:
  application:         # 服务名
    name: uid-center
  profiles:
    active: dev
  devtools:            # 热部署工具，需要在idea中同时设置auto compiler
    restart:
      enabled: true
      additional-paths: src/main/java, src/main/resources/application*
  datasource:
    url: jdbc:mysql://localhost:3306/uid-center?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: luc123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8849
        namespace: com-lc-dev
        file-extension: yaml
      discovery:
        server-addr: 127.0.0.1:8849
        namespace: com-lc-dev
        register-enabled: true
  config:
    import: nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8889/eureka/
#    register-with-eureka: true
#    fetch-registry: true

logging:
  config: classpath:./logback-lc.xml
  level:
    root: info
  file:
    path: ./${spring.application.name}/logs